### ISSUE TITLE
Add source license

### ISSUE THREAD

**Issue by ElectronicWar** [MarcoPNS/Spotify-Stream-Widget#2]
Currently, this project has no license and therefore is automatically fully copyrighted.
This makes it (nearly) impossible to contribute to the codebase.

**Comment by MarcoPNS** [comment]
Ups sorry... I now added the license 
https://github.com/MarcoPNS/Spotify-Stream-Widget/commit/affd4ededdd4f5dbe66d3342e3cc4e625d6197ae
