### ISSUE TITLE
Suggestion & Issue

### ISSUE THREAD

**Issue by cocas42** [MarcoPNS/Spotify-Stream-Widget#20]
hi,
how are you?

i i have 2 things today, first its the timer in my computer (i dont know if they have same problem in other computers!) time bumps every 2 seconds( ex: show 0:00 next Show 0:02; etc)

other thing its de design and function in name.
i see this website: https://spotify.aidenwallis.co.uk/ and i like to much design but its to late, yor program its more faster, can you change some design to the artis and track name? (maybe you dont need top bar and border on image

**Comment by MarcoPNS** [comment]
Hi @cocas42! Thanks for your Feedback but I do not understand you correctly. That the time jumps 2 seconds is a known bug. It is already fixed and you will not have the problem again in the next version. 

What do you mean with the design? What would you like to change. What additional options do you want?

**Comment by cocas42** [comment]
yes, time jumps, 
the design its because you can have a new design like  https://spotify.aidenwallis.co.uk/
![image](https://user-images.githubusercontent.com/26633523/70261165-c87fd280-1789-11ea-841f-111af8823740.png)

you can see the design in website i send only go to this link: and see design (you need play spotify)
![image](https://user-images.githubusercontent.com/26633523/70261300-0bda4100-178a-11ea-9706-35c18dc136ba.png)

**Comment by MarcoPNS** [comment]
Version 1.4 is live and have a export mode. now you can build your own overlay. 
https://github.com/MarcoPNS/Spotify-Stream-Widget/releases/tag/1.4.0.0
