### ISSUE TITLE
Viewer Issue 1.4.0.2

### ISSUE THREAD

**Issue by sethrdee** [MarcoPNS/Spotify-Stream-Widget#24]
When I change to a different song before the viewer gets to the end of the current song, it bugs out in a few ways. These viewer bugs are: 

- Visually freezing
- Cutting off the name of the song it was frozen on
- Combining the current song name and artist with the previous art
- Not recognizing the album artwork, with an error message that read, "An error occurred: The underlying connection was closed: An unexpected error occurred on a send."

In the first three instances, it would not advance to the next song, but be frozen on the previous one's album artwork and location in the scrubber. This issue would not work itself out even after multiple songs were played through afterwards.

Restarting the client, reselecting the viewer window, or closing the error window sometimes fixed this issue temporarily.

**Comment by MarcoPNS** [comment]
Thank you for your issue! Could you upload your log file? You can find it in the /logs folder.

**Comment by rob275** [comment]
This is happening to me also, log attached.

[2020-06-05.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/4737588/2020-06-05.log)

**Comment by MarcoPNS** [comment]
@rob275 are you sure? your log does not show a error that could trigger such a behavior.

@sethrdee just found out that you have a problem with the GetImageFromUri() Function which try to download the album cover. I try to fix it.

**Comment by MarcoPNS** [comment]
Update is live! Try it out: https://github.com/MarcoPNS/Spotify-Stream-Widget/releases/tag/1.4.0.3
