### ISSUE TITLE
http://localhost:4002/auth?code=

### ISSUE THREAD

**Issue by LithiumCFK** [MarcoPNS/Spotify-Stream-Widget#26]
Hello everybody.
After granting access to https://www.spotify.com/us/account/apps/, there is a redirect to http://localhost:4002/auth?code=....
The widget has a connection status

Tell me what could be the problem.

**Comment by MarcoPNS** [comment]
You could try to revoke your permission for the "Stream Widget for Spotify" and try it again.

**Comment by LithiumCFK** [comment]
Thanks, it worked
Glitch fix for next track in next update?

**Comment by MarcoPNS** [comment]
what glitch?

**Comment by LithiumCFK** [comment]
![Снимок](https://user-images.githubusercontent.com/38191359/84414173-47af0100-ac1a-11ea-9600-f36a88028a5e.PNG)
![Снимок2](https://user-images.githubusercontent.com/38191359/84414174-48479780-ac1a-11ea-809b-192c4d4064b3.PNG)
![Снимок3](https://user-images.githubusercontent.com/38191359/84414175-48e02e00-ac1a-11ea-9da0-5c7c96b5597b.PNG)
![Снимок4](https://user-images.githubusercontent.com/38191359/84414177-48e02e00-ac1a-11ea-9f97-f9ae7ebb1732.PNG)

**Comment by LithiumCFK** [comment]
After changing the track, the font size of the name does not change until you click on Widget

**Comment by MarcoPNS** [comment]
can you upload your log file?

**Comment by LithiumCFK** [comment]
[2020-06-11.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/4766071/2020-06-11.log)

**Comment by MarcoPNS** [comment]
since the glitch is out of context a bit I will close this issue and move everything related to the glitch to #27
