### ISSUE TITLE
Crash after browser redirects with auth code

### ISSUE THREAD

**Issue by JanineBat** [MarcoPNS/Spotify-Stream-Widget#28]
Hi,

I'm getting crashes when trying to connect my Spotify account, after the browser redirects to localhost:4002/auth?code=..., revoking access through my account page then trying again yields the same result.

The only log entries generated seem to be at the time of starting the widget, not the crash:

`2020/06/19 13:54:50 Call 0 [DEBUG] Application started - v1.4.0.3
2020/06/19 13:54:50 Call 0 [EXCEPTION] VersionCheck_DoWork() Exception: System.InvalidCastException: Conversion from string "1.4.0.3" to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   at Spotify_Stream_Widget.Settings.VersionCheck_DoWork(Object sender, DoWorkEventArgs e)`

and the Windows error reporting information from the crash window is:

`Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Stream Widget for Spotify.exe
  Problem Signature 02:	1.4.0.3
  Problem Signature 03:	5edcea9b
  Problem Signature 04:	Stream Widget for Spotify
  Problem Signature 05:	1.4.0.3
  Problem Signature 06:	5edcea9b
  Problem Signature 07:	c3
  Problem Signature 08:	c4
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789`

This is on Windows 7 Professional 64-bit, and the browser in question is Firefox 77.0.1 if that's relevant. Happens if I run the widget as admin, as well. Please let me know if you need any additional information.

**Comment by MarcoPNS** [comment]
Do you use any special anti virus software?

**Comment by JanineBat** [comment]
This was with Microsoft Security Essentials. I believe Windows Firewall was disabled.

Unfortunately, shortly after opening this issue my system disk got trashed by something, and I am no longer running Win7, so further information may be hard to gather.

**Comment by MarcoPNS** [comment]
belongs to #29
