### ISSUE TITLE
failed auth on win7

### ISSUE THREAD

**Issue by eksem666** [MarcoPNS/Spotify-Stream-Widget#29]
Good afternoon, when I connect my Spotify account, the app stops working I don't know what the problem might be...

but before all this a window appears with permission to access your Spotify account before termination 
and then http://localhost:4002/auth?code=

**Comment by MarcoPNS** [comment]
Maybe this could help: https://github.com/MarcoPNS/Spotify-Stream-Widget/issues/26#issuecomment-642655871

**Comment by eksem666** [comment]
it didn't help me, that's why I'm writing here

**Comment by MarcoPNS** [comment]
Which ant virus do you use? Which version of Windows do you use?

**Comment by eksem666** [comment]
I don't use antivirus / windows 7

**Comment by MarcoPNS** [comment]
win7 also got mentioned on #28 - never tested it on Win7 

Could be hard to fix since Microsoft doesn't update Win7 anymore but I try to set up a virtual machine to test it.
