### ISSUE TITLE
Status: Connected - not displaying track name

### ISSUE THREAD

**Issue by YourClosetLlama** [MarcoPNS/Spotify-Stream-Widget#31]
Hello!

I attempted to find a solution prior to reaching out here but couldn't seem to figure it out. I appear to be connecting to Spotify successfully (the app displayed "Status: Connected"), but the widget is displaying << Track Name >> and << Artist Name >> with the progress bar not responding to the current duration of the song. I've tried updating and redownloading but don't know enough about coding to mess with any files without assistance. Up until this point I have had no problems and have absolutely loved this project!

I appreciate any help :)

**Comment by MarcoPNS** [comment]
Hello!

Do you use Win10 or something else?

Can you upload your log file? You can find it in in the application folder under `/Logs/`

which anti virus do you use?

**Comment by YourClosetLlama** [comment]
I use W10 with 64-bit architecture. I (hopefully?) attached the log below. 
[2020-09-22.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/5266571/2020-09-22.log)

**Comment by MarcoPNS** [comment]
You use v1.4.0.3 according to the log. Could you try out v1.4.1.0?

https://github.com/MarcoPNS/Spotify-Stream-Widget/releases/tag/1.4.1.0

**Comment by YourClosetLlama** [comment]
I went to my recycle bin to dig out that old log because the new log didn't have anything that seemed useful in it... Here's the v1.4.1.0 log though. 
[2020-09-22.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/5266902/2020-09-22.log)

**Comment by YourClosetLlama** [comment]
I'm unsure why, but it seems to be working again. I haven't done anything differently but I figured I'd see on the off-chance a restart was all that was needed.
