### ISSUE TITLE
CPU usage is crazy high

### ISSUE THREAD

**Issue by ericblade** [MarcoPNS/Spotify-Stream-Widget#32]
On my laptop, CPU usage is constantly at about 15% -- it's pegging one core at maximum the whole time it runs.  This is absolutely obliterating my battery runtime, and my fans are constantly pegged because one core is always hot.

Anyone else experiencing anything like this?

**Comment by janesth** [comment]
Are you experiencing this while using this tool?

**Comment by MarcoPNS** [comment]
What are your hardware specs?

**Comment by ericblade** [comment]
Yes, much of the time when this is running, it is like this.  Seems like it might be related to something that occurs after I undock my laptop, as it's not happening right now, but I'm docked, and I just rebooted and started the app.  I'll grab a screengrab next time I see it happening.

i7-4900MQ 2.8Ghz, 16 gig ram, etc

**Comment by ericblade** [comment]
Despite having seen it quite several times before coming here and posting, I haven't been able to repeat it since, therefore, I'm going to close this.
