### ISSUE TITLE
switches keep true status

### ISSUE THREAD

**Issue by velociceratops** [MarcoPNS/Spotify-Stream-Widget#33]
widget doesnt save light mode when I switch to it. restarts are dark mode. Is this considered an issue? It saves all the other options i chose.

**Comment by MarcoPNS** [comment]
Just found out that all switches keep the "true" status. I'm not sure why this is happening and whether this is actually a .NET bug, but I'll see if it can be worked around.

**Comment by MarcoPNS** [comment]
Should be fixed with the new beta version: https://github.com/MarcoPNS/Spotify-Stream-Widget/raw/main/Release/Spot_Widget_1_5_0_2.zip
