### ISSUE TITLE
ADVERT - Artist

### ISSUE THREAD

**Issue by karnophage** [MarcoPNS/Spotify-Stream-Widget#4]
After changing playlists (to a different artist) this is displayed. It doesn't change.

![image](https://user-images.githubusercontent.com/9065745/38769546-60149cd8-4037-11e8-8b24-c37b516117f7.png)

**Comment by karnophage** [comment]
Hmm, after changing through a bunch of songs it did update.

**Comment by MarcoPNS** [comment]
Was this a local file? I also mentioned the problem with local .mp3 files which do not have any meta data. Also Spotify struggle with such files. You can not scroll trough such songs with Spotify. So it acts like a ad.

**Comment by karnophage** [comment]
No, not a local file, I only stream. Changing artists forced it to update which seemed to work. Meta was ok in Spotify itself though.

**Comment by MarcoPNS** [comment]
Ok does this happen after a ad? I guess I should start testing with the free version of Spotify and not always with the Premium version haha

**Comment by karnophage** [comment]
Not a free user either, I'm on premium.

**Comment by MarcoPNS** [comment]
Just published a new version. Please test it if this still happen: https://github.com/MarcoPNS/Spotify-Stream-Widget/releases/tag/1.2.0.0
