### ISSUE TITLE
the web page to log in disappears when I click "Connect to Spotify"

### ISSUE THREAD

**Issue by artroom219** [MarcoPNS/Spotify-Stream-Widget#48]
What happens in order

> "Connect to Spotify"

> Small window pops open "The Widget will open your browser to connect to the Spotify API" (I hit "Ok")

> Black window pops open for a frame then gone at same time Spotify Widget says it's trying to connect.

It's not my wifi or my connection also I have already tried resting my pc the same issue.

**Comment by MarcoPNS** [comment]
Hi! Sorry to hear that. What OS do you use? Have you already authorized Spotify?
