### ISSUE TITLE
Cannot Uninstall

### ISSUE THREAD

**Issue by wulfgunn** [MarcoPNS/Spotify-Stream-Widget#50]
Hello, I have enjoyed using the application but someone used my Spotify email to try to get into my bank account a day or so after I started using this. (I only used said email for subscriptions anyway so I cancelled it). Not 100% if this is on your end but I do wish to uninstall due to that problem. 

Other than that the application was easy to use during streams.

**Comment by MarcoPNS** [comment]
Hello! The app use a token swap authentication via the official Spotify API. It will only request access to the user-read-playback-state scope. That means that the app can only access the playback status but not your email or any other personal details.

You can't install the app. It's a portable app that does work out of the box. Just delete the files that you downloaded.

The problem with your email and your bank has nothing to do with this app. Maybe your login credentials got leaked somewhere. You can check out this page to check if your mail for compromised: https://haveibeenpwned.com/
