### ISSUE TITLE
Taskbar icon is always on main display

### ISSUE THREAD

**Issue by Whomsky** [MarcoPNS/Spotify-Stream-Widget#51]
If you have Multiple displays and 'Show taskbar buttons on...' is set to 'Taskbar where window is open', the Spotify Stream Widget's taskbar icon is always on the main taskbar, no matter the actual screen the application is on.
![image](https://user-images.githubusercontent.com/49082964/119252642-af512880-bbad-11eb-8575-6109d6df96c5.png)

**Comment by MarcoPNS** [comment]
I guess it is because of the settings window
