### ISSUE TITLE
Suggestion - View when Paused

### ISSUE THREAD

**Issue by stuntguy3000** [MarcoPNS/Spotify-Stream-Widget#55]
It would be nice for the widget to show when a song is paused.

Is this a feature that can be added?

**Comment by MarcoPNS** [comment]
like a pause icon over the album cover?

**Comment by stuntguy3000** [comment]
Yes, or some other visual indication that the playback is currently pasued.

**Comment by MarcoPNS** [comment]
is part of the beta version: https://github.com/MarcoPNS/Spotify-Stream-Widget/raw/main/Release/Spot_Widget_1_5_0_2.zip
