### ISSUE TITLE
Track Title and Album Art not showing even after using token

### ISSUE THREAD

**Issue by r3dg0d** [MarcoPNS/Spotify-Stream-Widget#62]
2021/12/30 10:17:30 Call 189 [DEBUG] Application started - v1.4.1.0
2021/12/30 10:22:04 Call 240 [DEBUG] Application started - v1.4.1.0

Application starts but doesn't load the Track Title and Album Art, it's just the placeholder values...
https://i.imgur.com/XsK7VQe.png

**Comment by BeLZeDaR666** [comment]
yeah i am getting the same, its a real shame as I love this app

**Comment by aussiedandan** [comment]
Same version, same issue :(

**Comment by BeLZeDaR666** [comment]
I think spotify have changed thier API as it now not working again and the fix i treid last time no longer works 
Windows 10. V1.4.1.0

**Comment by chefgeorges** [comment]
I have exactly the same problem since the last Spotify update.

**Comment by MarcoPNS** [comment]
It should still work

![image](https://user-images.githubusercontent.com/35105681/190922411-7201e479-c35d-499e-a42d-9605424bc231.png)

I can push a small update with no real change, just a fresh build to see if it works. Maybe the certificate in the app is out to date.

**Comment by MarcoPNS** [comment]
Just released v1.5 - please try it out 😊

**Comment by haze-howlingwolf** [comment]
Mine is not showing any info too, just the initial values. I'm not using any VPN and not from Russia.
![imagem_2022-09-19_220518855](https://user-images.githubusercontent.com/113953918/191145130-a125760d-acc6-4f5e-a19b-dea5474c780f.png)

**Comment by BeLZeDaR666** [comment]
> Just released v1.5 - please try it out 😊

V1.5 is not working for me still just get the name holders like the image above

**Comment by MarcoPNS** [comment]
**Troubleshooting guide**

- If you have the problem, then first delete the app from your pc. 
- After that go into your Spotify account and remove access to the "Stream Widget for Spotify" app. You should find it here: https://www.spotify.com/account/apps/
- Now download the latest version of the app and extract the complete .zip archive. You should find it here: https://github.com/MarcoPNS/Spotify-Stream-Widget/releases
- Launch the app and click on "Connect to Spotify". 
- If you are asked about a firewall, please allow connections to the app. 
- If you are redirected to the Spotify website, do not log in yet. Open the http://localhost:4002/auth website first - this will take you to the web server that the app sets up to receive data from Spotify. You should see a "500 - Internal Server Error". If you don't see that, then please let me know.
- Proceed to the Spotify website and allow the app to access your data. After that, the widget app should say "Connected". Start a song on Spotify and after a few seconds you should see the info.

Please let me know how far you get with this. Thanks :)

**Comment by toxinburn** [comment]
having the same issue followed all steps i get the internal error etc as i should however still does not function

**Comment by toxinburn** [comment]
was like this right before update perhaps the token in config is incorrect i dunno

**Comment by MarcoPNS** [comment]
Could you try out this beta release? This version uses a slightly different auth process. If the authorization fails, then the following message appears over the "Connect to Spotify" button: "Status: Auth Failed. Please try again"" https://github.com/MarcoPNS/Spotify-Stream-Widget/raw/main/Release/Spot_Widget_1_5_0_1.zip

**Comment by toxinburn** [comment]
> 

2022/09/21 12:57:48 Call 0 [DEBUG] Application started - v1.5.0.1
2022/09/21 12:57:52 Call 0 [DEBUG] Starting Auth Process...
2022/09/21 12:57:55 Call 0 [DEBUG] Auth was successful

it's getting auth but just not displaying track and or album cover still.

**Comment by MarcoPNS** [comment]
As there are two versions of the Spotify desktop app - one from the spotify website and one from the Microsoft app store, could you try to [install](https://support.spotify.com/article/reinstall-spotify/) the one you do not currently have to see if that would make any difference.

**Comment by BeLZeDaR666** [comment]
V1.5.1 works with windows store version
V1.5.1 does NOT work with direct from spotify here

**Comment by MarcoPNS** [comment]
@BeLZeDaR666 I stumbled across this issue in the Spotify Forum. There is currently a bug where the Spotify App does not report the current track to the API. At the same time Spotify connect does not work and you could even start a song in a different app version to play two tracks at the same time because of that.

This is something that needs to be fixed by Spotify unfortunately.

**Comment by BeLZeDaR666** [comment]
@MarcoPNS No problems it is working with the Windows store version for me so I am using that for now

**Comment by toxinburn** [comment]
Well mine just magically started working again out of the blue without even changing to the windows store version .
