### ISSUE TITLE
Windows 11 Crashed 

### ISSUE THREAD

**Issue by Tomich1337** [MarcoPNS/Spotify-Stream-Widget#64]
Hello dear creator, I use your software to output songs to broadcast , thank you very much, I recently upgraded to Win11, and I play on a custom screen resolution of 4:3, on a full hd monitor, and when I launch your software, I go into the game and collapse it, my computer stops responding and becomes dead, it is not even possible to call the task manager, only reboot through the button, I hope you can fix it if you need help write

**Comment by Tomich1337** [comment]
There was no such thing on win 10

**Comment by MarcoPNS** [comment]
Hello!
Can you upload your log file? You can find it in in the application folder under `/Logs/`

**Comment by MarcoPNS** [comment]
Could you update to v1.5 and try it again?

**Comment by MarcoPNS** [comment]
Could you try out this beta release? https://github.com/MarcoPNS/Spotify-Stream-Widget/raw/main/Release/Spot_Widget_1_5_0_1.zip
