### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN on trying to connect

### ISSUE THREAD

**Issue by Decebalus777** [MarcoPNS/Spotify-Stream-Widget#65]
Trying to connect to the Spotify API gives a DNS_PROBE_FINISHED_NXDOMAIN error, the website for the token swap may not be working anymore?

**Comment by MarcoPNS** [comment]
Maybe check your DNS Service. https://spotify-token-swap.camefrom.space/ should be up and running.
