### ISSUE TITLE
Track and Album are empty in the widget.

### ISSUE THREAD

**Issue by chefgeorges** [MarcoPNS/Spotify-Stream-Widget#70]
Since the latest Spotify update, even correctly connected, the "Track" and "Album" information appears empty.
----
Depuis la dernière mise-à-jour de Spotify, même correctement connecté, les informations "Piste" et "Album" apparaissent vide.
![2022-09-18 18_48_08-Rocket League (64-bit, DX11, Cooked)](https://user-images.githubusercontent.com/90694179/190918639-561fe053-53cc-4e9b-bef9-611e935e00e4.png)

**Comment by MarcoPNS** [comment]
Hi! Sorry but I can't verify the bug. 

![image](https://user-images.githubusercontent.com/35105681/190922246-33cab7c8-79d5-42bb-8edd-5be61427c7bf.png)

Can you upload your log file? You can find it in in the application folder under `/Logs/`

**Comment by purelure** [comment]
same for me but i'm living in Russia :(

log file:

[2022-09-19.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/9595598/2022-09-19.log)

**Comment by purelure** [comment]
logfile text:

2022.09.19 07:24:14 Call 0 [DEBUG] Application started - v1.5.0.0
2022.09.19 07:25:24 Call 12 [DEBUG] Application started - v1.5.0.0
2022.09.19 07:26:08 Call 12 [DEBUG] Application started - v1.5.0.0
2022.09.19 07:27:04 Call 12 [DEBUG] Application started - v1.5.0.0
2022.09.19 07:28:30 Call 38 [EXCEPTION] GetPlayback() Exception: System.AggregateException: Произошла одна или несколько ошибок. ---> System.Net.Http.HttpRequestException: Произошла ошибка при отправке запроса. ---> System.Net.WebException: Запрос был прерван: Запрос отменен.
   в System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   в System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Конец трассировки внутреннего стека исключений ---
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   в System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   в System.Threading.Tasks.Task`1.get_Result()
   в SpotifyAPI.Web.SpotifyWebClient.DownloadRaw(String url, Dictionary`2 headers)
   в SpotifyAPI.Web.SpotifyWebClient.Download(String url, Dictionary`2 headers)
   в SpotifyAPI.Web.SpotifyWebClient.DownloadJson[T](String url, Dictionary`2 headers)
   в SpotifyAPI.Web.SpotifyWebAPI.DownloadDataAlt[T](String url)
   в SpotifyAPI.Web.SpotifyWebAPI.DownloadData[T](String url)
   в SpotifyAPI.Web.SpotifyWebAPI.GetPlayback(String market)
   в Spotify_Stream_Widget.Viewer.VB$StateMachine_44_UpdateTrack.MoveNext() в C:\Users\marco\Sites\Spotify-Stream-Widget\Spotify Stream Widget\Viewer.vb:строка 264
---> (Внутреннее исключение #0) System.Net.Http.HttpRequestException: Произошла ошибка при отправке запроса. ---> System.Net.WebException: Запрос был прерван: Запрос отменен.
   в System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   в System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Конец трассировки внутреннего стека исключений ---<---

2022.09.19 07:33:18 Call 38 [DEBUG] Application started - v1.5.0.0

**Comment by MarcoPNS** [comment]
@purelure I'm not sure if I made a mistake in the release package... Could you make a complete clean installation? Delete the old folder, download the zip again and see if it works. 👍

**Comment by purelure** [comment]
Spotify work with another Region account, right now i use Turkish account

i reload zip archive, still no songname, but status is "connected"

Sadge.

**Comment by purelure** [comment]
also stream deck BarRaider spotify app don't work too, same problem with connect "linking account" :/

**Comment by MarcoPNS** [comment]
Do you use a VPN? I guess connections from Russia are getting blocked.

**Comment by purelure** [comment]
nah, if i use VPN - i just have status "connecting..." xd 


btw, topic starter is not me, maybe this guy from another country

**Comment by Adolamin** [comment]
> also stream deck BarRaider spotify app don't work too, same problem with connect "linking account" :/

Same issue. Aftering using the updates software my Spotify actually is like disconnected from my account LOL like, I can listen to spotify on my browser on the same account, and also listen to my spotify app, on the same account(both online) listening to two completely different songs.

Streamdeck Spotify plugin stopped working too.

**Comment by MarcoPNS** [comment]
@purelure @Adolamin Unfortunately, I am not able to provide support for Russia. Spotify probably prohibits access to the API from Russia. A proxy could possibly fix the problem, but I can't promise anything there. As for that, unfortunately, I can't do anything more.

@chefgeorges I would like to move this topic to https://github.com/MarcoPNS/Spotify-Stream-Widget/issues/62 - closed for now

**Comment by Adolamin** [comment]
> @purelure @Adolamin Unfortunately, I am not able to provide support for Russia. Spotify probably prohibits access to the API from Russia. A proxy could possibly fix the problem, but I can't promise anything there. As for that, unfortunately, I can't do anything more.
> 
> @chefgeorges I would like to move this topic to #62 - closed for now

I live in Canada :)

**Comment by MarcoPNS** [comment]
As there are two versions of the Spotify desktop app - one from the spotify website and one from the Microsoft app store, could you try to [install](https://support.spotify.com/article/reinstall-spotify/) the one you do not currently have to see if that would make any difference.
