### ISSUE TITLE
Not getting Track Info

### ISSUE THREAD

**Issue by AusOmen** [MarcoPNS/Spotify-Stream-Widget#77]
App says that it's connected to the Spotify API but no track data is retrieved.
App version is 1.5.0.2 which was only recently updated. previous version 1.5.0.0 was also this way.

Screen shot and log file attached.

![Screenshot 2022-09-28 194623](https://user-images.githubusercontent.com/114574649/192747766-e9712db7-ed91-424d-b432-639e9b4ac5c6.jpg)
[2022-09-28.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/9663703/2022-09-28.log)

**Comment by MarcoPNS** [comment]
Hi! Could you try a different Spotify App? Like the Web App or the windows store version? There is a bug in some spotify apps where the Playback will not be transmitted to the API
