### ISSUE TITLE
Still does not update with Streamlabs Chatbot or Nightbot song requests

### ISSUE THREAD

**Issue by PixelFilter** [MarcoPNS/Spotify-Stream-Widget#8]
The issue still persists.

When I use Streamlabs Chatbot or Nightbot, the artwork and song name does not change. Only the status bar changes. It basically defaults to the first song's artwork for the entire playlist.

**Nightbot:** https://beta.nightbot.tv/
**Chatbot:** https://streamlabs.com/chatbot

**Comment by MarcoPNS** [comment]
There was an update on the API. I will try to test it and see if this will fix the problem.
https://github.com/JohnnyCrazy/SpotifyAPI-NET/commit/50dd3985684619ef89dd387ff27f33bb5b6b193c

**Comment by MarcoPNS** [comment]
Just tested everything and it seems to work without any problems. I will upload the new version: v1.2.1.0

![image](https://user-images.githubusercontent.com/35105681/39966135-1aa4ced0-56a7-11e8-8722-71f14b82483a.png)

I will close this issue now.
