### ISSUE TITLE
app is shutting down

### ISSUE THREAD

**Issue by morver1** [MarcoPNS/Spotify-Stream-Widget#81]
when i log in to spotify the app shuts down the situation repeats all the time

**Comment by MarcoPNS** [comment]
Hi! Thank your the info. Can you upload your log file? You can find it in in the application folder under /Logs/

**Comment by morver1** [comment]
[2022-11-15.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/10106006/2022-11-15.log)
sorry for that long

**Comment by MarcoPNS** [comment]
I'm sorry but I don't have a solution at this point for the Desktop Version. Are you interested trying out the beta of the web version in this case? You can send me a mail [beta@widgetapp.stream](mailto:beta@widgetapp.stream) so I can support you setting everything up.
