### ISSUE TITLE
App won't stop showing update pop-up

### ISSUE THREAD

**Issue by BortFPS** [MarcoPNS/Spotify-Stream-Widget#85]
I have updated to Version 1.5.0.0 however the app continues to prompt me to check out the new version.

**Comment by MarcoPNS** [comment]
Hi! Thank your the info. Can you upload your log file? You can find it in in the application folder under /Logs/

**Comment by BortFPS** [comment]
Hi Marco, I uninstalled and reinstalled as per the previous ticket I opened and that seems to have fixed it. Thank you!
