### ISSUE TITLE
Choosing a different font

### ISSUE THREAD

**Issue by lemon-sh** [MarcoPNS/Spotify-Stream-Widget#87]
I don't see an option to change the default font of the widget. I think it would be an easy to implement, but quite important feature.

**Comment by MarcoPNS** [comment]
Thank you for your feedback and feature request regarding the font of the Spotify widget. At the moment, we are currently focusing on developing the web version of the widget and will take your request into consideration for future updates.

**Comment by MarcoPNS** [comment]
You can use custom fonts in the new web app: https://widgetapp.stream/
