### ISSUE TITLE
App wont connect to spotify

### ISSUE THREAD

**Issue by lordz0mbies** [MarcoPNS/Spotify-Stream-Widget#91]
Been using this app for a few months now but suddenly it wont connect to spotify, just says "the site cannot be reached" whenever i try to connect

**Comment by vanishedher0** [comment]
having the same issue and the homepage seems to be down somehow...

**Comment by MrRexe** [comment]
Same issue. Widget can't connect to homepage/server

**Comment by Thae13** [comment]
Same here

**Comment by MarcoPNS** [comment]
Should be fixed.
