### ISSUE TITLE
Widget does not open at all

### ISSUE THREAD

**Issue by cosmixdust** [MarcoPNS/Spotify-Stream-Widget#93]
Hello, I downloaded the latest ver and upon trying to open it, it doesn't do anything at all. It doesn't open the widget nor does it open the browser to link with my Spotify account.

**Comment by MarcoPNS** [comment]
Hi! Can you explain what you have done before? Did you clicked on the connect button? Which settings do you use?

**Comment by deltastro** [comment]
Before that I just downloaded the .zip file and moved all of the items to a new folder. Then I tried opening the app but doesn't do anything.
May I ask what settings are you asking specifically? Is it the OBS ones?

**Comment by MarcoPNS** [comment]
No, I'm speaking about the widget. So you double click on the .exe and nothing happens? No icon in the taskbar? Do you have a antivirus that could block it?

**Comment by deltastro** [comment]
Exactly, I double click on the .exe and nothing happens.
The only antivirus I have is Windows Defender, but I didn't get some sort of notification that could detect the .exe as "virus" or something related.

**Comment by MarcoPNS** [comment]
I'm sorry but I don't have a solution at this point for the Desktop Version. Are you interested trying out the beta of the web version in this case? You can send me a mail beta@widgetapp.stream so I can support you setting everything up.
